eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8081

spring:
  application:
    name: "api-gateway"
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: authentication-service
          uri: http://localhost:9099/
          predicates:
            - Path=/authenticationService/**

        - id: booking-service
          uri: http://localhost:9089/
          predicates:
            - Path=/bookingService/**

        - id: chat-service
          uri: http://localhost:9095/
          predicates:
            - Path=/chatService/**

        - id: customer-service
          uri: http://localhost:9096/
          predicates:
            - Path=/customerService/**

        - id: email-service
          uri: http://localhost:9097/
          predicates:
            - Path=/emailService/**

        - id: payment-service
          uri: http://localhost:9098/
          predicates:
            - Path=/paymentService/**

        - id: registration-service
          uri: http://localhost:9082/
          predicates:
            - Path=/registrationService/**

        - id: review-service
          uri: http://localhost:9083/
          predicates:
            - Path=/reviewService/**

        - id: transporter-service
          uri: http://localhost:8090/
          predicates:
            - Path=/transporterService/**

        - id: product-webapp
          uri: http://localhost:7777/
          predicates:
            - Path=/webapp/**
