name: Codacy Analysis
env:
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
run-name: |
    curl -L https://download.codacy.com/2.0.0/linux/codacy-coverage-reporter-assembly.jar -o codacy-coverage-reporter-assembly.jar
    java -jar codacy-coverage-reporter-assembly.jar report -l Java -r target/site/jacoco/jacoco.xml -t $CODACY_PROJECT_TOKEN


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package
    - name: Test
      run: mvn test

      
    
      

